name: CI Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install
        working-directory: ./nimishreact-app

      - name: Run tests
        run: npm test -- --passWithNoTests
        working-directory: ./nimishreact-app

      - name: Build project
        run: npm run build
        working-directory: ./nimishreact-app
